### ISSUE TITLE
Multiple inheritance of Controller

### ISSUE THREAD

**Issue by fairking** [zHaytam/SmartBreadcrumbs#1]
Found some small issues, please take a look at screenshot bellow.
My controllers are a bit complex. 
```
public abstract class BaseController : Controller
public abstract class ViewController : BaseController
public class HomeController : ViewController
```

The same issue might happen with return types (`IActionResult`, `Task<IActionResult>`) It can be `JsonResult` for example or some `CustomResult`.

![untitled111](https://user-images.githubusercontent.com/13495631/42008835-791d77b8-7a7f-11e8-8a13-28e4f1fb3aa5.png)

Thanks for your little component which does a huge job. Regards.

**Comment by fairking** [comment]
My fixes below. There are more than described in the Issue.
[SmartBreadcrumbs.zip](https://github.com/zHaytam/SmartBreadcrumbs/files/2143834/SmartBreadcrumbs.zip)

**Comment by fairking** [comment]
Some more fixes:
[SmartBreadcrumbs2.zip](https://github.com/zHaytam/SmartBreadcrumbs/files/2150390/SmartBreadcrumbs2.zip)

Tested in my project. working perfectly.

**Comment by zHaytam** [comment]
Thanks, I'll look at this asap!

**Comment by zHaytam** [comment]
Pushed your modifications and uploaded the new version to nuget, it should be available shortly. Thanks again!

**Comment by fairking** [comment]
No problem my friend. I am working on MenuTagHelper. Looking forward to share my code if you are interesting.
