### ISSUE TITLE
An unhandled exception occurred while processing the request. ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

### ISSUE THREAD

**Issue by bodzilla** [zHaytam/SmartBreadcrumbs#13]
I keep running into this issue:

```
An unhandled exception occurred while processing the request.
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```

I've only set up one breadcrumb which is the home, here's the code:

```
        [DefaultBreadcrumb("Home")]
        public async Task<IActionResult> Index()
        {
            var user = await _userService.GetByEmailAsync(User.Identity.Name, x => x.Oysters);
            return View(user);
        }
```

Any help on this? I'm using v1.4

**Comment by zHaytam** [comment]
Hi,
There was a open PR about this bug (.net core 2.2) and I didn't even see it, sorry...
Can you confirm that it fixes the bug? (Nuget package version 1.0.4.1).

**Comment by bodzilla** [comment]
Hi @zHaytam, I don't see the new version up on Nuget yet.

**Comment by zHaytam** [comment]
It's currently validating.

**Comment by bodzilla** [comment]
Ok, please let me know when this becomes available :)

**Comment by zHaytam** [comment]
It's now listed, please check again ^^

**Comment by bodzilla** [comment]
Works like a charm now, many thanks for the fix and the quick response!
