### ISSUE TITLE
Startup options not working in 1.0.4.1

### ISSUE THREAD

**Issue by MeanGreen11** [zHaytam/SmartBreadcrumbs#15]
We were using version 1.0.3.3 and liking it. We upgraded to version 1.0.4.1 recently, but the options defined in ConfigureServices are no longer working at all. Specifically 'options.ActiveLiClasses = "breadcrumb-item active";' didn't work anymore, the class was not being added in our razor views. 

On most Actions we simply use '[Breadcrumb("ViewData.Title", CacheTitle = true, FromController = nameof(DashboardController), FromAction = nameof(DashboardController.Index))]', but this resulted in the actual text "ViewData.Title" being rendered in the page.
Downgrading to 1.0.3.3 resolved both issues.

On a sidenote: In the https://github.com/zHaytam/SmartBreadcrumbs#options section, the part "options." is missing for each of the 6 lines.

**Comment by zHaytam** [comment]
Hi, I'm glad you're using SmartBreadcrumbs!
I will look into this and get back to you as soon as I can!

**Comment by MeanGreen11** [comment]
Thanks for the fast reply. It seems there may be an issue on my end I failed to see up to now, I'll look into that first!

**Comment by zHaytam** [comment]
Also, I don't get your side node;
What "options" part is missing?

I did forget to update the readme to include 2 new options though (`LiTemplate `& `ActiveLiTemplate`).

**Comment by MeanGreen11** [comment]
The example is not valid, it should be

                services.UseBreadcrumbs(GetType().Assembly, options =>
                {
                    options.TagName = "nav";
                    options.TagClasses = "";
                    options.OlClasses = "breadcrumb";
                    options.LiClasses = "breadcrumb-item";
                    options.ActiveLiClasses = "breadcrumb-item active";
                    options.SeparatorElement = "<li class=\"separator\">/</li>";
                });

**Comment by zHaytam** [comment]
Oh my god you're right!
What a silly mistake...

**Comment by zHaytam** [comment]
I looked at all the modifications that happened from 1.0.3.3 to 1.0.4.1 and there doesn't seem to be a problem with the options :/
I'll wait for your answer and if everything is fine, I will be pushing a new version containing icons.

**Comment by zHaytam** [comment]
I'm closing this, assuming you fixed the problem 😃
