### ISSUE TITLE
Make library as netstandard, not netcoreapp

### ISSUE THREAD

**Issue by Kharabet** [zHaytam/SmartBreadcrumbs#20]
Hi @zHaytam ,

When i tried to use your package in my class library, I've got an error:
`error NU1202: Package SmartBreadcrumbs 1.0.3.3 is not compatible with netstandard2.0 (.NETSt
andard,Version=v2.0). Package SmartBreadcrumbs 1.0.3.3 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0) `

So I found the solution.  (According this [issue](https://github.com/dotnet/sdk/issues/1728)). You should make it as netstandard that anyone can use it in all their projects. Not only in web project.

Thank you

**Comment by zHaytam** [comment]
Indeed it the library should use .NET Standard instead.
I will fix this in the next update, thank you!

**Comment by Kharabet** [comment]
I've just created a pull request (#21).
I think now this issue should be closed.
