### ISSUE TITLE
ArgumentException When Decorating Action Overload(s)

### ISSUE THREAD

**Issue by AggieEngineer2k** [zHaytam/SmartBreadcrumbs#23]
If an MVC controller has two `Add()` action overloads, one decorated with `[HttpGet]` and the other with `[HttpPost]`, the following exception is thrown.

`System.ArgumentException: An item with the same key has already been added. Key: Forms.Add`
  `at System.Collections.Generic.Dictionary.TryInsert(TKey key, TValue value, InsertionBehavior behavior)`
  `at SmartBreadcrumbs.BreadcrumbManager.Initialize(Assembly assembly)`
  `at SmartBreadcrumbs.Extensions.ServiceCollectionExtensions.AddBreadcrumbs(IServiceCollection services, Assembly assembly, BreadcrumbOptions options)`

It seems to behave correctly only having decorated the `[HttpGet]` action with `[Breadcrumb]`.  Could this scenario be added to the documentation, or could keys be distinguished by the action method signature?  I didn't try with multiple `[HttpGet]` overloads.

**Comment by zHaytam** [comment]
Hello, good catch!
Thing is, if we add the action's type (Get, Post, ...) to the keys then you would need to also change your `FromAction` to have them, or maybe have GET by default or something.
And then when using the taghelper, it should be able to see whether the called action/controller is GET or POST and try to find the key that way, and I'm not sure it's possible, I'll have to check.

**Comment by ConnerOrth** [comment]
I think you can check for other attributes on a given method to determine if it's a GET or POST or any other HttpMethod.
You could them append the method to the BreadcrumbNode.Key if the method is anything other then the default (I think GET is a reasonable default like you suggested)

This would require a change to `ExtractMvcKey` method to handle appending the method to the key.

And within the taghelper you can check the context for the request method type.
`ViewContext.HttpContext.Request.Method`

Change `GetNodeKey` to take httpmethod into account.

@zHaytam
