### ISSUE TITLE
BreadcrumbAttribute should only be allowed on methods and classes

### ISSUE THREAD

**Issue by ConnerOrth** [zHaytam/SmartBreadcrumbs#25]
(Default)BreadcrumbAttribute have no effect when placed on anything besides methods or classes.
Make this apparent by added AttributeTargets restrictions such as:
`[AttributeUsage(AttributeTargets.Method | AttributeTargets.Class, AllowMultiple = false, Inherited = true)]`

**Comment by zHaytam** [comment]
I already added that on my local version and didn't want to push until a new version is out.
Thank you for the reminder!
