### ISSUE TITLE
SmartBreadcrumbs does not work with MVC area

### ISSUE THREAD

**Issue by jbp17** [zHaytam/SmartBreadcrumbs#26]
I have a MVC .net core Web Application.  I have a HomeController in the root controller folder.  I also have a EmployersController in the Employer folder under the areas.  When I click on Add Employer, it will put the breadcrumb correctly like "Home/Add Employer" with the URL (http://localhost:49932/Employer/Employers/AddEmployer) .  However, when I click on Home to go back to home, it took me to http://localhost:49932/Employer, which I guess to be the home of that area.  Is it possible to let it take me to http://localhost:49932/, which is the index URL for HomeController?

**Comment by zHaytam** [comment]
Can you please create a sample project and link it to me so that I try it?

**Comment by zHaytam** [comment]
Will close this due to inactivity.
Please re-open if you have more details!
