### ISSUE TITLE
More than one DefaultBreadcrumb or option to hide it

### ISSUE THREAD

**Issue by rutenio** [zHaytam/SmartBreadcrumbs#31]
Hello,
Is it possible to add more than one DefaultBreadcrumb or hide it with some option? I'm in a scenario where the application has 4 modules for different user groups (departments). A "Home" option is not very feasible since once you access the system in your specific module, it will hardly change the module because you would not have permissions to do so. Ideally each module would have its "Home"

**Comment by zHaytam** [comment]
Hi, how would you know which default breadcrumb to use?
I'm asking so that we brainstorm an idea.

**Comment by rutenio** [comment]
I thought DefaultBreadcrumb is used as root only if a "Root" is not defined. Something in this drawing. You would have to create the "Root" option. Or a bool for "UseRoot", if false (Default = true) the path starts from the current point.

**Comment by zHaytam** [comment]
Basically an option where if true, the check for a default breadcrumb is removed?
I guess if developers use this options they need to take responsibility, hum..

**Comment by rutenio** [comment]
I think that currently you already check all the path according to FromAction and FromController. So you mount the path to the source. The only difference is that if the last object does not have these parameters defined it still has the option "UseAsRoot" = true (maybe it makes more sense), it becomes the first breadcrumb item

**Comment by zHaytam** [comment]
I added an option `DontLookForDefaultNode` in 2.1.0.
If you set it to true (in `services.AddBreadcrumbs(assembly, options => { ... })` then it won't check for the default node (and it won't use it neither), this means you'll always need to be sure that the last node in your path is the one you actually want to be first.

**Comment by rutenio** [comment]
Thanks, man!
