### ISSUE TITLE
InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by Dutchman163** [zHaytam/SmartBreadcrumbs#32]
Hello,

I have a run-time error while starting the app with SmartBreadcrumbs.
The error points to the Startup File:
![image](https://user-images.githubusercontent.com/8875726/57379710-b87a2300-71a7-11e9-978d-d35f414522e1.png)
The startupfile looks exactly like is descriped:
![image](https://user-images.githubusercontent.com/8875726/57379774-d9427880-71a7-11e9-9e55-a2852c23f22a.png)
The Default Node has been set. Other than that there are not yet other nodes set.

Does anyone know the cause of this problem?

**Comment by zHaytam** [comment]
Are you sure you set the default node?
`Single` is only used when trying to find the default node.

**Comment by zHaytam** [comment]
Any news about this problem?

**Comment by Dutchman163** [comment]
Jess, I had commented the default node. It works now!

**Comment by crypto-perry** [comment]
Hi there, I am facing a similar problem I think. Where do I set the default node?

**Comment by zHaytam** [comment]
Hello, you use the `DefaultBreadcrumb` attribute.

**Comment by crypto-perry** [comment]
I see, thanks
