### ISSUE TITLE
Actions with the same name in different areas

### ISSUE THREAD

**Issue by rutenio** [zHaytam/SmartBreadcrumbs#33]
Is there any way to debug a key duplicity error?
I changed the entire system structure to use areas and now there are some controllers with the same name. I try to run the debug but the maximum I get is the duplicate key (Home.Index), but I do not know how to solve it.
Thanks.

**Comment by zHaytam** [comment]
Hum, I guess I need to add the Area name to the key.
Something like: `Area.Controller.Action`.

**Comment by rutenio** [comment]
would be awesome!

**Comment by zHaytam** [comment]
I've been trying to implement these for 2 days now, hoping that I won't need to refactor a lot of base code and I don't seem to get it...
I'm sorry but I don't think it's a good idea to change as much code for this, maybe if I get some time for it.
For now, you'll have to change the name of your controller or your action :/

**Comment by rutenio** [comment]
I can help you, if you want.

**Comment by nsathiyamoorthi** [comment]
Is there any plan to implement this anytime soon?

**Comment by zHaytam** [comment]
Personally, I won't have much time the next 4 weeks as I'm close to finish up my masters degree / internship.
Although if anyone wants to work on it and create a PR I would be more than happy to accept it.
