### ISSUE TITLE
Passing parameters to action when manually creating nodes

### ISSUE THREAD

**Issue by ghost** [zHaytam/SmartBreadcrumbs#34]
Hi!

First, thanks for your amazing work!

Second, I just updated to the 2.0.0 version and I can't seem to find how to pass parameters to my actions justlike we did in the previous version:

var childNode1 = new BreadcrumbNode("Action 1", "Home", "Action1", null, **new { id = 10 }**);

Thank you,

Victor

**Comment by ghost** [comment]
Found it!

`         var selectedUserNode = new MvcBreadcrumbNode("ApplicationSelection", "Permissions", user.Fullname)
         {
            RouteValues = new { username },
            Parent = usersNode
         };`

I didn't think I could see your code, so when I realized I could do that I managed to find what I was looking for.

Thank you,

Victor

**Comment by DivineLawnmower** [comment]
Hi,

Apologies, I could not understand what was required from the above.

If I have a page where I need to pass Ids as parameters as they are below: https://i.gyazo.com/36b40fd7fd9c842a2b0b428c2d6244e7.png

Is it possible to click on the nav link built by the breadcrumbs and pass one or two ids? This would need to be the case for most of the generated links I use in fact.

Any ideas?

Kind regards,
Matt

**Comment by zHaytam** [comment]
You need to use the `RouteValues` property on your manually created nodes in order to pass parameters to your link, just like adding `asp-route-...`.

**Comment by shmulyeng** [comment]
If I use the RouteValues property, the values get added as query string parameters. Is it possible to have RouteValues added as part of the route? 
Basically, I have a route that takes 4 parameters. It looks something like this:
http://url/locations/ny/nyc/sky/234
How would I get the breadcrumb to link to that?
