### ISSUE TITLE
Unable to add breadcrumb attribute for 2 MVC Action with same name in different Area

### ISSUE THREAD

**Issue by nsathiyamoorthi** [zHaytam/SmartBreadcrumbs#37]
![smartBreadCrumbs_Error](https://user-images.githubusercontent.com/26634613/59204965-cb4d9200-8b6f-11e9-82b0-ffe68da53657.PNG)

**Comment by nsathiyamoorthi** [comment]
we have 2 Areas in our project. 
- AdminPortal
- Compliance

Both areas have controller named "Dashboard" with action "Index".  Adding SmartBreadCrumbs in this scenario throws the error "An item with the same key has already been added". 

Adding AreaName in the BreadCrumb attribute doesnot resolve this  [Breadcrumb(Title = "Compliance Dashboard", AreaName = "Compliance")]

**Comment by zHaytam** [comment]
Please see issue #33

**Comment by zHaytam** [comment]
Fixed by #66
