### ISSUE TITLE
add localizations?

### ISSUE THREAD

**Issue by icesasoftcorp** [zHaytam/SmartBreadcrumbs#41]
how can i add Breadcrumb translations?

**Comment by zHaytam** [comment]
It is not possible at the moment, PRs are welcome though, it shouldn't be that hard to implement. If I get the time for it I'll do it.

Duplicate of #28

**Comment by markchipman** [comment]
One thought I have to accomplish this, although kludgey, would be to have the route for each endpoint have language specific routing (ie "/en/account" vs "/es/cuenta", etc.) and have the breadcrumb use them in conjunction with the correct language translations).

However it seems to me that really, the most direct (.net) way would be to _add an additional optional argument to the breadcrumb attribute_ to pass in the name of the resource resolver.  That way your doing translations using the same key, but getting the correct translated value back.
