### ISSUE TITLE
url parameter on  SmartBreadcrumbs

### ISSUE THREAD

**Issue by clashjedsada** [zHaytam/SmartBreadcrumbs#42]
How to add parameter on SmartBreadcrumbs.

Thank you.

**Comment by ssheth01** [comment]
Hello zHaytam I was wondering the same. Is there a way to pass a parameter to SmartBreadCrumbs? Specifically the "FromAction" string? Thanks.

**Comment by zHaytam** [comment]
Hello, no it's not possible because attribute values need to be constant. However, you can do it using Manual Nodes, check the wiki ^^

**Comment by ssheth01** [comment]
Thank-you. Will do.
