### ISSUE TITLE
Async operations with ValueTask

### ISSUE THREAD

**Issue by gioullis** [zHaytam/SmartBreadcrumbs#43]
Does the library support async operations with ValueTasks? 
For example the following code does not work but if i change the ValueTask to Task it is working fine
`
[Breadcrumb("Cars")]
        public async ValueTask<IActionResult> Index()
        {
            var carTypes = await PopulateVesselTypesDropDownAsync();
            ViewData["carTypes "] = carTypes ;
            return View();
        }
`

**Comment by zHaytam** [comment]
Right now, no. This is related to #38 and I will be fixing it very soon, sorry for the delay!
