### ISSUE TITLE
Migrate to .NET Core 3.0?

### ISSUE THREAD

**Issue by ab-Colin** [zHaytam/SmartBreadcrumbs#44]
Are planning to migrate the project to .NET Core 3.0 soon?

**Comment by zHaytam** [comment]
Yes, of course. Can't say a date though.
It'll probably come when some other issues are solved too, but it shouldn't take a lot of time.

I'll see if I can do it this weekend!

**Comment by ab-Colin** [comment]
Thanks!

**Comment by roman-fidalia** [comment]
Waiting to try this in my .NET Core 3.0 project, as other libraries out there didn't do the trick.

**Comment by andrecj93** [comment]
Yeah this seems really cool to implement under de dependency injection. Wa trying this on my project with Razor Pages, but couldn't get it to work. Its its not showing anything, I setup everything correctly. Is it because Im using .net core 3.0?

**Comment by zHaytam** [comment]
Hi, its done! You can use the v3 of the NuGet package.
