### ISSUE TITLE
Breadcrumbs display only in <li> elements?

### ISSUE THREAD

**Issue by bryancass** [zHaytam/SmartBreadcrumbs#48]
I installed the NuGet package as directed in the Wiki article.  The breacrumbs are displaying on my views as list elements:

1. Home
2. Contact Us
3. Support
4. Knowledge Base

I would like them to display like this:

Home > Contact Us > Support > Knowledge Base

There is no explanation about how to do this that I can find.  Can you help?  Is this set up in options?

Thanks!

**Comment by zHaytam** [comment]
Are you using Bootstrap?

**Comment by bryancass** [comment]
Hi - No I don't use bootstrap (not intentionally).  I have my own CSS that I maintain.  Is there a library or something I have to include to make it work without the <ol> list?
Thanks!
Bryan
    On Friday, December 20, 2019, 04:12:22 PM EST, Haytam Zanid <notifications@github.com> wrote:  
 
 
Are you using Bootstrap?

**Comment by zHaytam** [comment]
Then you'll have to style the breadcrumb `<ol>` with some custom CSS too. This library is based on Bootstrap but gives you the ability to change the CSS classes used, but it doesn't style the breadcrumbs itself, that's for the user to do, since every website is different.

Hope I helped!

**Comment by bryancass** [comment]
OK thank you Haytam!  Do you have a suggestion on how to do that?  I know C# pretty well, but am new to CSS.  I see that I can change the class in Startup.cs for the OL tag.  What would the <OL> class look like to make the breadcrumbs line up horizontally instead of vertically?  If you give me a starting point, then I'm sure I can figure it out from there.  Maybe tell me which Bootstrap class it's currently using and then I can copy that into my site.css and play with it?  

Thanks for your help!
Bryan

    On Saturday, December 21, 2019, 5:45:07 AM EST, Haytam Zanid <notifications@github.com> wrote:  
 
 
Then you'll have to style the breadcrumb <ol> with some custom CSS too. This library is based on Bootstrap but gives you the ability to change the CSS classes used, but it doesn't style the breadcrumbs itself, that's for the user to do, since every website is different.

Hope I helped!

**Comment by zHaytam** [comment]
You could take inspiration from the w3schools example [here](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_breadcrumbs).

I'll be closing this issue as it's not related to SmartBreadcrumbs anymore, good luck!

**Comment by bryancass** [comment]
Thank you, Haytam, that helps me a lot.  :-) 

Bryan

    On Monday, December 23, 2019, 5:00:45 AM EST, Haytam Zanid <notifications@github.com> wrote:  
 
 
You could take inspiration from the w3schools example here.

I'll be closing this issue as it's not related to SmartBreadcrumbs anymore, good luck!
