### ISSUE TITLE
Support for Razor Pages 

### ISSUE THREAD

**Issue by GocePetrovski** [zHaytam/SmartBreadcrumbs#5]
Would be good if this was working with project that uses Razor pages only. 
Reason being that Microsoft is recommending RP as the preferred approach.

From [Create a web app with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-2.1)
> We recommend you try the Razor Pages tutorial before the MVC/Controller/Views version. The Razor Pages tutorial:
Is the preferred approach for new application development.
Is easier to follow.
Covers more features.

**Comment by zHaytam** [comment]
Hello and thanks for the request, It would be good to include Razor Pages indeed.

Would people prefer it to be in a new branch/repository (e.g. SmartBreadcrumbs.RazorPages) with a new nuget package and everything or would you prefer it to be in the same project (SmartBreadcrumbs)?

Right now I'm checking if I will have to include extra packages, if yes then mvc people will have to use razor pages packages and vise versa, which I think is a bit not practical.

**Comment by zHaytam** [comment]
I just checked some stuff in Razor Pages and I will have to create a new project, probably call it SmartBreadcrumbs.RazorPages and modify it using the RP packages.

Will see if I can get the time to do this soon.

**Comment by ageisen2000** [comment]
Any updates on this? Or is there any beta packages I might be able to try out?

**Comment by zHaytam** [comment]
Not at this time, I was in an internship and just got back few weeks ago to school.
I am still planning on supporting Razor Pages, will try to do so as soon as possible!
Sorry for the delay.

**Comment by pbros** [comment]
Any news for Razor Pages support?

**Comment by RuiAAPereira** [comment]
Hello, great work!
Have news for Razor Pages?

**Comment by zHaytam** [comment]
Hello,
It turns out that I finally got a project that uses Razor Pages so I will most likely add its support in SmartBreadcrumbs this week (18/03 - 24/03)!

**Comment by RuiAAPereira** [comment]
Great news, looking forward to it! ;D

**Comment by pbros** [comment]
I wound up using https://github.com/cloudscribe/cloudscribe.Web.Navigation instead, which allowed me to manage the main navigation and breadcrumbs. You do however have to manually manage the structure in XML

**Comment by zHaytam** [comment]
I have started refactoring almost all the code in order to make it cleaner as well as being able to handle both MVC and Razor Pages.
~~It will, however, require a bit of refactoring on your ends too (e.g. BreadcrumbAttribute becomes MvcBreadcrumbAttribute).~~

**Comment by zHaytam** [comment]
Hello, I'm happy to say that SmartBreadcrumbs 2.0.0 is released, which is a complete rewrite!
You can get it from NuGet now.

If you encounter any problem, please open a new issue ASAP!
I changed the README to make it lighter and will write a Wiki soon to compensate.

**PS: There are some breaking changes, please check the readme/docs**
