### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by tusharbsale** [zHaytam/SmartBreadcrumbs#51]
I am getting error as 'Sequence contains no matching element'

I am working on .net core 2.2 application and  i had set DefaultBreadcrumb in my HomeController and Breadcrumb attribute in remaining Controllers action methods but on startup.cs in services.AddBreadcrumbs(GetType().Assembly) line getting error as Sequence contains no matching element.

Can anyone facing similar issue ?can anyone guide regarding same.

**Comment by zHaytam** [comment]
Hello, is it possible for you to send me a project where I can reproduce the issue? Since you say you have a `DefaultBreadcrumb` set up, it's hard for me to know where the problem is :/

**Comment by tusharbsale** [comment]
Hi, I have uploaded my project in git.
https://github.com/tusharbsale/BatchJob

**Comment by tusharbsale** [comment]
> Hello, is it possible for you to send me a project where I can reproduce the issue? Since you say you have a `DefaultBreadcrumb` set up, it's hard for me to know where the problem is :/

Hi, just identified that if action method is defined as `async Task<ActionResult>` then it is not getting picked up in list of breadcrumbs. for ex. my action method used in project is '`public async Task<ActionResult> Index()`'

Can you pls check

**Comment by zHaytam** [comment]
Ah yes, SmartBreadcrumbs only looks for `IActionResult` right now... Is there a reason why you're using the implementation instead of the interface? Using the interface is always preferred.

**Comment by tusharbsale** [comment]
Thanks. I am changing my method to `IActionResult` now and it is working now. Cool Stuff :-)

**Comment by bstoddart** [comment]
Hello,

I am using the 3.6.1 version of SmartBreadcrumbs and I have the same problem.  I have confirmed that I am using IActionResult.  Is there something else I should inspect.

**Comment by bstoddart** [comment]
Sorry, I figured it out!  I need to have a least 1 breadcrumb :)
