### ISSUE TITLE
Two times encoded ViewData.Title titles when using OverwriteTitleOnExactMatch

### ISSUE THREAD

**Issue by pesik77** [zHaytam/SmartBreadcrumbs#54]
When you have ViewData.Title title with OverwriteTitleOnExactMatch, then is in your code two times applied _htmlEncoder.Encode(...) method. When you use some word with special chars (ex. Domů), you get wrong display result.

**Comment by zHaytam** [comment]
Fixed in 3.5.2! Sorry for the huge delay.
