### ISSUE TITLE
How can use Smartbreadcrumbs in blazor

### ISSUE THREAD

**Issue by HsaeedAhmad** [zHaytam/SmartBreadcrumbs#55]
I tried to use like this

namespace BreadcrumbSample.Data
{

    [Breadcrumb]
    public class WeatherForecastService
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };
        [DefaultBreadcrumb("My Home")]
        public Task<WeatherForecast[]> GetForecastAsync(DateTime startDate)
        {
            var rng = new Random();
            return Task.FromResult(Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = startDate.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            }).ToArray());
        }
        [Breadcrumb("About us")]
        public string AboutUs()
        {
            // In this case, the DefaultNode will be the parent of this node.
            return "About";
        }
     
   

        [Breadcrumb("Contact us", FromAction = "WeatherForecastService.AboutUs")]
        public string ContactUs()
        {
            // This page is a child of the About us page
            return "";
        }

    }
}
//In my stratup file
      services.AddBreadcrumbs(GetType().Assembly, options =>
            {
                // Testing
                options.DontLookForDefaultNode = true;
            });

But i get noting

**Comment by zHaytam** [comment]
Hello!  
SmartBreadcrumbs was not made for Blazor, so I don't think it'll work unfortunately.  
**Maybe** in a future version.
