### ISSUE TITLE
SmartBreadCrumbsException - No Node Exists

### ISSUE THREAD

**Issue by BrenMcM** [zHaytam/SmartBreadcrumbs#58]
Hi,
I am trying to implement Breadcrumbs into a small  MVC App with a single controller. However, I keep getting the exception "No Node Exists the has ReviewApplication as a Key"

Even though I have Breadcrumbs setup for this Action e.g.

[Breadcrumb("ReviewApplication", FromAction = "Apply_Step4")
public async Task<IActionResult> ReviewApplication() { ... }

[Breadcrumb("EditApplication", FromAction = "ReviewApplication")
public async Task<IActionResult> EditApplication() { ... }

**Comment by zHaytam** [comment]
Can you try to set the `FromAction` like this: `ControllerName.ReviewApplication`?

**Comment by zHaytam** [comment]
I'm assuming your issue was fixed?
Feel free to re-open.
