### ISSUE TITLE
Incompatibility with net461

### ISSUE THREAD

**Issue by AlexStefann** [zHaytam/SmartBreadcrumbs#6]
Hi zHaytam,

I am having an issue with using SmartBreadcrumbs, i can't install the NuGet package because my project has Target Framework 4.6.1 which is newer than netcoreapp2.0. 
Will this be supported in the near future and do you have an estimate for it? Or is there a workaround that i could try?

Unfortunately i cannot change the TargetFramework version because of the other projects in the solution and their dependencies.

Thanks in advance,
Alex

**Comment by zHaytam** [comment]
Are you using ASP.NET MVC or ASP.NET Core?
Because I don't understand your problem :/

**Comment by AlexStefann** [comment]
I am using ASP.NET Core on top of net461, i mananged to copy the source files and it compiled, so i can now use SmartBreadcrumbs

Thank You
