### ISSUE TITLE
Unable to add breadcrumb attribute for Razor page with same page name in an Area

### ISSUE THREAD

**Issue by biomade** [zHaytam/SmartBreadcrumbs#62]
I have a razor page in the main part of the application [/Pages/Index.cshtml]
I also have an area named StyleGuide which has an index page in the root [/Area/StyleGuide/Pages/Index.cshtml]
When I launch the solution an error is thrown in the 

The error is thrown in the StartUp.cs in the ConfigureServices method at the services.AddBreadcrumbs(GetType().Assembly)  call.
The error is: _**An item with the same key has already been added. Key: /Index**_

**Comment by zHaytam** [comment]
Ah, yes... This is related to #37, which is still not implemented unfortunately.  
Sorry, I'll try to see if I have the time for it this week.
