### ISSUE TITLE
How to Create several levels of Nodes

### ISSUE THREAD

**Issue by biomade** [zHaytam/SmartBreadcrumbs#63]
Background:
I have pages in the main area of the application (/Pages/Index.cshtml, /Pages/Categories/xx.cshtml, /Pages/Products/xx.cshtml)
and I have pages in 2 areas (/Area1/Pages/xx, and /Area2/Pages/xxx)

I would like the bread crumbs in the areas to be like Home (root)/Home1 (area1 root)/xxx.cshtml

Is this possible and how?

**Comment by zHaytam** [comment]
You can use manual nodes and do any configuration you want, see https://github.com/zHaytam/SmartBreadcrumbs/wiki/4.-Manual-nodes

**Comment by biomade** [comment]
Thank you for the information, I will implement it later today.
