### ISSUE TITLE
Solved:  Support for Razor Class Library (also how to use Razor Pages in Areas)

### ISSUE THREAD

**Issue by carolinemilam** [zHaytam/SmartBreadcrumbs#64]
Because reflection is used to parse all the breadcrumb attributes, if you use controllers or razor pages in Razor Class Library (outside your application's assembly), you need a way to pass its assembly to the SmartBreadcrumbs constructor.

Added additional methods to ServiceCollectionExtensions.cs:

public static void AddBreadcrumbs(this IServiceCollection services, Assembly[] assembly)
        {
            AddBreadcrumbs(services, assembly, new BreadcrumbOptions());
        }

        public static void AddBreadcrumbs(this IServiceCollection services, Assembly[] assembly, Action<BreadcrumbOptions> optionsSetter)
        {
            var options = new BreadcrumbOptions();
            optionsSetter.Invoke(options);
            AddBreadcrumbs(services, assembly, options);
        }

        private static void AddBreadcrumbs(IServiceCollection services, Assembly[] assembly, BreadcrumbOptions options)
        {
            var bm = new BreadcrumbManager(options);
            foreach(Assembly a in assembly)
            {
                bm.Initialize(a);
            }
            
            services.AddSingleton(bm);

            services.TryAddSingleton<IActionContextAccessor, ActionContextAccessor>();
        }

Then, just created an assembly array in Startup.cs:
Assembly[] assemblies = new Assembly[] { GetType().Assembly, typeof(MyApp.Models.BrandConfig).Assembly };
            services.AddBreadcrumbs(assemblies, options =>
            {
                options.TagName = "nav";
                options.TagClasses = "";
                options.OlClasses = "breadcrumb";
                options.LiClasses = "breadcrumb-item";
                options.ActiveLiClasses = "breadcrumb-item active";
                options.SeparatorElement = "<li class=\"separator\"> > </li>";
                options.DontLookForDefaultNode = true;
            });

(MyApp.Models.BrandConfig is just a static class in the razor class library - you can pick any class in your library).

Also, had trouble getting this to work with Razor Pages nested in areas.  Some of the posts indicate this does not work with areas, but was able to get it to work by specifying the AreaName in the attribute.  Example used in scaffolding Core 3.1 Identity pages:

using SmartBreadcrumbs.Attributes;

namespace MyApp.Areas.Identity.Pages.Account.Manage
{
    [Breadcrumb("Email", FromPage = typeof(IndexModel), AreaName = "Identity")]
    public partial class EmailModel : PageModel { ...

**Comment by zHaytam** [comment]
Hello, sorry for the delay. Can you create a Merge Request with these changes?
Concerning the Areas, it doesn't work when 2 areas have an action with the same name, that's the issue.

**Comment by bunda3d** [comment]
@carolinemilam is there any way you could point to a github repo where you did this? I feel like I get it, but can't quite make it work. I'm in the same use case as you show (one of my areas is Identity). I like what you're doing but am not sure what all classes you created to make the reflection work and so far can't get a build. 
---

> Because reflection is used to parse all the breadcrumb attributes, if you use controllers or razor pages in Razor Class Library (outside your application's assembly), you need a way to pass its assembly to the SmartBreadcrumbs constructor.
> 
> Added additional methods to ServiceCollectionExtensions.cs:
> 
> public static void AddBreadcrumbs(this IServiceCollection services, Assembly[] assembly)
> {
> AddBreadcrumbs(services, assembly, new BreadcrumbOptions());
> }
> 
> ```
>     public static void AddBreadcrumbs(this IServiceCollection services, Assembly[] assembly, Action<BreadcrumbOptions> optionsSetter)
>     {
>         var options = new BreadcrumbOptions();
>         optionsSetter.Invoke(options);
>         AddBreadcrumbs(services, assembly, options);
>     }
> 
>     private static void AddBreadcrumbs(IServiceCollection services, Assembly[] assembly, BreadcrumbOptions options)
>     {
>         var bm = new BreadcrumbManager(options);
>         foreach(Assembly a in assembly)
>         {
>             bm.Initialize(a);
>         }
>         
>         services.AddSingleton(bm);
> 
>         services.TryAddSingleton<IActionContextAccessor, ActionContextAccessor>();
>     }
> ```
> 
> Then, just created an assembly array in Startup.cs:
> Assembly[] assemblies = new Assembly[] { GetType().Assembly, typeof(MyApp.Models.BrandConfig).Assembly };
> services.AddBreadcrumbs(assemblies, options =>
> {
> options.TagName = "nav";
> options.TagClasses = "";
> options.OlClasses = "breadcrumb";
> options.LiClasses = "breadcrumb-item";
> options.ActiveLiClasses = "breadcrumb-item active";
> options.SeparatorElement = "<li class="separator"> > ";
> options.DontLookForDefaultNode = true;
> });
> 
> (MyApp.Models.BrandConfig is just a static class in the razor class library - you can pick any class in your library).
> 
> Also, had trouble getting this to work with Razor Pages nested in areas. Some of the posts indicate this does not work with areas, but was able to get it to work by specifying the AreaName in the attribute. Example used in scaffolding Core 3.1 Identity pages:
> 
> using SmartBreadcrumbs.Attributes;
> 
> namespace MyApp.Areas.Identity.Pages.Account.Manage
> {
> [Breadcrumb("Email", FromPage = typeof(IndexModel), AreaName = "Identity")]
> public partial class EmailModel : PageModel { ...

**Comment by zHaytam** [comment]
Do you also need this option?

**Comment by carolinemilam** [comment]
Hi,

I am new to this forum - this is a test to see if I can reply to the email.  Please confirm if message comes through.

Caroline

**Comment by zHaytam** [comment]
Yes it does, you can reply to GitHub issues using an email too.

**Comment by carolinemilam** [comment]
Great!

So, I actually made further changes to fix bugs i introduced and then I realized the whole design requires a unique model class name so Area Razor Page indexes need to be named uniquely (e.g. MyNamespace.Areas.CodeManager.CodeManagerIndexModel vs MyNamespace.Areas.CodeManager.IndexMode. Since I’m at beginning of project, an acceptable solution, but you may want to address before incorporating my changes in case someone is adding this to existing solution.

I am away from office and will work on getting you source code with a change log next week.

Regards,
Caroline

**Comment by bunda3d** [comment]
> Do you also need this option?

I believe so. 

I'm working on a project that has both MVC Views (with controllers) and also some folders with Areas and Razor Pages. This Project is part of a Solution that is deployed as a Nuget package on an internal Nuget server; therefore it is SHARED by other projects & solutions, which use it as a presentation layer (it has corporate-wide CSS, theme-ing, branding assets, the Microsoft Identity pages for authentication and authorization, etc...). 

Because of other solutions using the presentation solution (which has the SmartBreadcrumb Nuget pkg installed), it can complicate the breadcrumbs service. I may have got the Default breadcrumb to work for various solutions by assigning it in the Presentation solution project to 'relative home' of ` "~/" `.  But not sure if it will hold up in further testing. And I may instead instruct the middleware to _ignore_ Default breadcrumb (as @carolinemilam does) if that makes it work better.

But it seemed like @carolinemilam  is using reflection and loading StartUp.cs services in a manner similar to how other utilities have been implemented in our shared presentation solution, and was looking for more detail around that to see if I can get SmartBreadcrumbs to work for our presentation layer.

**Comment by bunda3d** [comment]
> Great! So, I actually made further changes to fix bugs i introduced and then I realized the whole design requires a unique model class name so Area Razor Page indexes need to be named uniquely (e.g. ...


I don't want to bother you, but do you have any updates on how you got this to work? (like a repo with code samples?) 
I'm at the end of my sprint and will need to do something else or drop this if I can't get it to work well soon.

Thanks again for any help

**Comment by zHaytam** [comment]
Doesn't the sample project already include a working example of areas working?

**Comment by bunda3d** [comment]
Sorry, I thought @carolinemilam was doing something different from your sample project?  It's not just Areas I'm looking at, I have a shared solution that acts as the base presentation layer for several other solutions. I thought @carolinemilam was doing something similar with her StartUp.cs method calling an array of Assembly[]. Is that not the case?
