### ISSUE TITLE
Area Support - Generating non-area parent urls incorrectly includes the area value of the current page

### ISSUE THREAD

**Issue by sethsteenken** [zHaytam/SmartBreadcrumbs#69]
Generating a parent url for an action or controller that is not part of an Area while on a page that is part of an Area causes the parent urls to assume the Area of the current page. This is because `IUrlHelper.Action` will use the current page's _area_ route value when generating the url even if `null` is supplied as the `RouteValues` parameter.

`string GetUrl(IUrlHelper urlHelper) => urlHelper.Action(Action, Controller, RouteValues);`

When RouteValues above is _null_ (_AreaName_ not specified on `BreadcrumbAttribute`), the route value _area_ on the current page is supplied when generating the url.

Looks like node url generating logic needs to explicitly include an empty area in the route values for nodes that do not specify an area. Something like this on `BreadcrumbNode` constructor:

Current:

```
if (!string.IsNullOrWhiteSpace(areaName))
{
	RouteValues = new
	{
		area = areaName
	};
}
```

New:

```
RouteValues = new
{
	area = areaName?.Trim() ?? string.Empty
};
```

This way, for controllers and actions that are not under an Area, the route values will explicitly say `{ area = string.Empty }` so the url helper will generate the url properly. What do you think? My preliminary testing checks out. I'd be glad to make a pull request for this, but wanted to run it by someone else. Thanks!

**Comment by zHaytam** [comment]
Hello, you are right, this problem is indeed present. Your solution seems to be good, a PR would be very welcomed! Thank you

**Comment by julianyus** [comment]
Hello, any idea when this bug will be fixed?
