### ISSUE TITLE
ASP.NET Core Areas

### ISSUE THREAD

**Issue by AlexStefann** [zHaytam/SmartBreadcrumbs#7]
Hi,
Can i use SmartBreadcrumbs with Areas? Or does it need some special customization?

As example, you can check this link to see what i am talking about:
https://stackoverflow.com/questions/36535511/how-to-use-an-area-in-asp-net-core

Thank You

**Comment by zHaytam** [comment]
Hi,
It depends wheter getting the url to a page works using `Url.GetAction(action, controller)`. You'll have to try this and get back to me okay?

Have a nice day!

**Comment by ahmedgaduo1** [comment]
it's not working with Areas
Url is http://localhost:8888/events/EventFront/index
and bread crumb generate this
![firefox_screenshot_2018-11-11t13-12-27 497z](https://user-images.githubusercontent.com/12746616/48313412-d1bd6080-e5c4-11e8-8989-0d03a78dd59c.png)
events is the area..

**Comment by ashokreddyHub** [comment]
Hi zHaytam,

I am getting the following error while installing for NuGet, I am trying to install it into .NETFramework,Version=v4.6.1 and ASP.Net Core MVC application.

`Package SmartBreadcrumbs 1.0.3.3 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package SmartBreadcrumbs 1.0.3.3 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)	`

Thank you!

**Comment by zHaytam** [comment]
SmartBreadcrumbs only works with ASP.NET Core, not normal MVC (which explains your error).

**Comment by ashokreddyHub** [comment]
Thank you for your response.
