### ISSUE TITLE
Bug: Doesn't seem to support Razor Page areas.

### ISSUE THREAD

**Issue by ajtatum** [zHaytam/SmartBreadcrumbs#70]
This was exactly what I was looking for; however, I ran into issues as soon as I started to implement the Breadcrumb attribute in on Razor pages in Areas. The format structure is different from your tests, they look like: Areas > Area Name > Pages. So, right now, for example, I have a "Blog" area, and even though I specify the below:

```
     [Area("Blog")]
     [Breadcrumb("Blog", AreaName = "Blog", FromPage = typeof(WebAppName.Web.Pages.IndexModel))]
```

I get an error that there's already a key /Index. This is because, I have a root IndexModel for the home page and then an IndexModel for the Blog area.

I briefly looked through your code and I couldn't tell where a change would be required. However, I figured I'd post and let you know as you know your code best.

Thank you,
AJ

**Comment by zHaytam** [comment]
Hello, sorry for the delay!

I'm not 100% sure I understand your problem, but did you check the sample project? Areas there have the same action name I believe.
