### ISSUE TITLE
Startup SmartBreadcrumbs GetType().Assembly Error

### ISSUE THREAD

**Issue by joamsantos** [zHaytam/SmartBreadcrumbs#81]
Good evening,

I'm getting this error when I add SmartBreadcrumbs in my services.
As you can see:

`services.AddBreadcrumbs(GetType().Assembly);`

I configured my services as it is in the Wiki.

When I tried to run the application, I got this error:

`An error occurred while starting the application.
InvalidOperationException: Sequence contains no matching element
System.Linq.ThrowHelper.ThrowNoMatchException()

InvalidOperationException: Sequence contains no matching element
System.Linq.ThrowHelper.ThrowNoMatchException()
System.Linq.Enumerable.Single<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
SmartBreadcrumbs.BreadcrumbManager.GenerateHierarchy(Dictionary<string, BreadcrumbNodeEntry> entries)
SmartBreadcrumbs.BreadcrumbManager.Initialize(Assembly assembly)
SmartBreadcrumbs.Extensions.ServiceCollectionExtensions.AddBreadcrumbs(IServiceCollection services, Assembly assembly, BreadcrumbOptions options)
SmartBreadcrumbs.Extensions.ServiceCollectionExtensions.AddBreadcrumbs(IServiceCollection services, Assembly assembly)
TasksDo.App.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
+
            services.AddBreadcrumbs(GetType().Assembly);
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(object instance, IServiceCollection services)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder+<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
Microsoft.AspNetCore.Hosting.StartupLoader+ConfigureServicesDelegateBuilder<TContainerBuilder>+<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(object instance, IServiceCollection services)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder+<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
Microsoft.AspNetCore.Hosting.StartupLoader+ConfigureServicesDelegateBuilder<TContainerBuilder>+<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.WebHost.Initialize()
Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
TasksDo.App.Program.Main(string[] args) in Program.cs
+
            CreateWebHostBuilder(args).Build().Run();`

Can you help me to fix this particullary issue?

**Comment by zHaytam** [comment]
Do you have a `DefaultBreadcrumb`?

**Comment by joamsantos** [comment]
@zHaytam I think not.

I need to created it??

**Comment by zHaytam** [comment]
Yes, almost all websites should have a default page (e.g. Home/Index page).
See https://github.com/zHaytam/SmartBreadcrumbs/wiki/2.-Default-Page

**Comment by zHaytam** [comment]
Hopefully this helped you, feel free to re-open if not.
