### ISSUE TITLE
How to remove index entry from generated breadcrumbs?

### ISSUE THREAD

**Issue by midasw** [zHaytam/SmartBreadcrumbs#85]
Hello

Instead of having the index or home entry to show up in front of all breadcrumbs, I would like to have the option to disable it.

For example, I have an area called Manage, with an EmployeesController, of which the resulting breadcrumb would look like this:

`Home / Manage / Employees / Action name`

While I would like to just have:

`Manage / Employees / Action name`

Is this possible?

**Comment by midasw** [comment]
I've been able to achieve the desired behavior by disabling `DefaultBreadcrumb`, setting `DontLookForDefaultNode` to true as follows:

```
services.AddBreadcrumbs(GetType().Assembly, options =>
{
    options.TagName = "nav";
    options.TagClasses = "";
    options.OlClasses = "breadcrumb";
    options.LiClasses = "breadcrumb-item";
    options.ActiveLiClasses = "breadcrumb-item active";
    // Disable default node:
    options.DontLookForDefaultNode = true;
});
```

**Comment by zHaytam** [comment]
Hello,

That's exactly how it should be done. Feel free to close the issue if you don't have any other questions.

**Comment by riverahugo** [comment]
SmartBreadcrumbsException: FuncionariosController doesn't contain a valid action named Index.
I have this problem with my action of my controller. I don't want to use Index action for default. 
I use, 
 options.DontLookForDefaultNode = true;
and doesn't work.
I need help, and I using net core 2.1
