### ISSUE TITLE
Sequence Contains No Elements

### ISSUE THREAD

**Issue by clockwiseq** [zHaytam/SmartBreadcrumbs#87]
I followed the instructions on your main page and all I get is the following:

![image](https://user-images.githubusercontent.com/6662538/118373756-02a7f300-b57e-11eb-8349-64739101fc4c.png)

**Comment by zHaytam** [comment]
Hello,
Did you make sure to have a default breadcrumb?

**Comment by clockwiseq** [comment]
I did not.  The instructions here on GitHub don't mention anything about a default breadcrumb or how to use it.  I had to find your website and the page for it to know that you have to add the attribute to an action to make it work.  I still couldn't make it work for my case as I have areas.

**Comment by zHaytam** [comment]
It's mentioned in the Wiki. Are you using razor pages?

**Comment by clockwiseq** [comment]
Razor Views, sorry, I missed the Wiki link at the top.
