### ISSUE TITLE
Default Action

### ISSUE THREAD

**Issue by riverahugo** [zHaytam/SmartBreadcrumbs#91]
"Internal Server Error SmartBreadcrumbsException: FuncionariosController doesn't contain a valid action named Index."

I have this problem with my action of my controller. I don't want to use Index action for default.
I use,
options.DontLookForDefaultNode = true; on startup.cs
and doesn't work.

I need help, and I using net core 2.1

**Comment by zHaytam** [comment]
Hello,
Please use the `DefaultAction` option, which is set to `Index` by default.
