### ISSUE TITLE
Localized title

### ISSUE THREAD

**Issue by sylvaincaillot** [zHaytam/SmartBreadcrumbs#94]
Hi, 

I have a multilingual site and I tried the following for having localized breadcrumbs:
`[DefaultBreadcrumb(Resources.Generic.ResourceManager.GetString("Node.News"))]`

However, I keep getting the following error:
`Error CS0182 An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type`

I remember there was PR on this matter but I don't see how to easily implement localized bredcrumbs.

Thank you

**Comment by zHaytam** [comment]
Hello,
You can take a look at the example project. You need to specify the resource type that contains your localizations:
```cs
services.AddBreadcrumbs(GetType().Assembly, options =>
{
    // Testing
    options.DontLookForDefaultNode = true;
    options.ResourceType = typeof(Resx.BreadcrumbResources);
});
```

And the library should use it for your titles.
